provider:
  name: openfaas
  gateway: ${OPENFAAS_GATEWAY:-http://localhost:8080}

functions:
  image-classifier:
    lang: python3
    handler: ./image-classifier
    image: ${DOCKER_REGISTRY:-your-registry}/image-classifier:latest
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio:9000}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_SECURE: ${MINIO_SECURE:-false}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 128Mi
      cpu: 100m

  image-upload:
    lang: python3
    handler: ./image-upload
    image: ${DOCKER_REGISTRY:-your-registry}/image-upload:latest
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio:9000}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_SECURE: ${MINIO_SECURE:-false}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      KAFKA_TOPIC_IMAGE_UPLOADS: ${KAFKA_TOPIC_IMAGE_UPLOADS:-image-uploads}
    limits:
      memory: 512Mi
      cpu: 300m
    requests:
      memory: 128Mi
      cpu: 100m 